// 此文件由脚本自动生成，请勿手动修改
import { ImageSourcePropType } from 'react-native';

export type CardImageKey = 'Ace of Cups' | 'Ace of Pentacles' | 'Ace of Swords' | 'Ace of Wands' | 'Death' | 'Eight of Cups' | 'Eight of Pentacles' | 'Eight of Swords' | 'Eight of Wands' | 'Five of Cups' | 'Five of Pentacles' | 'Five of Swords' | 'Five of Wands' | 'Four of Cups' | 'Four of Pentacles' | 'Four of Swords' | 'Four of Wands' | 'Judgement' | 'Justice' | 'King of Cups' | 'King of Pentacles' | 'King of Swords' | 'King of Wands' | 'Knight of Cups' | 'Knight of Pentacles' | 'Knight of Swords' | 'Knight of Wands' | 'Nine of Cups' | 'Nine of Pentacles' | 'Nine of Swords' | 'Nine of Wands' | 'Page of Cups' | 'Page of Pentacles' | 'Page of Swords' | 'Page of Wands' | 'Queen of Cups' | 'Queen of Pentacles' | 'Queen of Swords' | 'Queen of Wands' | 'Seven of Cups' | 'Seven of Pentacles' | 'Seven of Swords' | 'Seven of Wands' | 'Six of Cups' | 'Six of Pentacles' | 'Six of Swords' | 'Six of Wands' | 'Strength' | 'Temperance' | 'Ten of Cups' | 'Ten of Pentacles' | 'Ten of Swords' | 'Ten of Wands' | 'The Chariot' | 'The Devil' | 'The Emperor' | 'The Empress' | 'The Fool' | 'The Hanged Man' | 'The Hermit' | 'The Hierophant' | 'The High Priestess' | 'The Lovers' | 'The Magician' | 'The Moon' | 'The Star' | 'The Sun' | 'The Tower' | 'The World' | 'Three of Cups' | 'Three of Pentacles' | 'Three of Swords' | 'Three of Wands' | 'Two of Cups' | 'Two of Pentacles' | 'Two of Swords' | 'Two of Wands' | 'Wheel of Fortune';

export const CARD_IMAGES: Record<CardImageKey, ImageSourcePropType> = {
  'Ace of Cups': require('../assets/cards/Ace of Cups.jpg'),
  'Ace of Pentacles': require('../assets/cards/Ace of Pentacles.jpg'),
  'Ace of Swords': require('../assets/cards/Ace of Swords.jpg'),
  'Ace of Wands': require('../assets/cards/Ace of Wands.jpg'),
  'Death': require('../assets/cards/Death.jpg'),
  'Eight of Cups': require('../assets/cards/Eight of Cups.jpg'),
  'Eight of Pentacles': require('../assets/cards/Eight of Pentacles.jpg'),
  'Eight of Swords': require('../assets/cards/Eight of Swords.jpg'),
  'Eight of Wands': require('../assets/cards/Eight of Wands.jpg'),
  'Five of Cups': require('../assets/cards/Five of Cups.jpg'),
  'Five of Pentacles': require('../assets/cards/Five of Pentacles.jpg'),
  'Five of Swords': require('../assets/cards/Five of Swords.jpg'),
  'Five of Wands': require('../assets/cards/Five of Wands.jpg'),
  'Four of Cups': require('../assets/cards/Four of Cups.jpg'),
  'Four of Pentacles': require('../assets/cards/Four of Pentacles.jpg'),
  'Four of Swords': require('../assets/cards/Four of Swords.jpg'),
  'Four of Wands': require('../assets/cards/Four of Wands.jpg'),
  'Judgement': require('../assets/cards/Judgement.jpg'),
  'Justice': require('../assets/cards/Justice.jpg'),
  'King of Cups': require('../assets/cards/King of Cups.jpg'),
  'King of Pentacles': require('../assets/cards/King of Pentacles.jpg'),
  'King of Swords': require('../assets/cards/King of Swords.jpg'),
  'King of Wands': require('../assets/cards/King of Wands.jpg'),
  'Knight of Cups': require('../assets/cards/Knight of Cups.jpg'),
  'Knight of Pentacles': require('../assets/cards/Knight of Pentacles.jpg'),
  'Knight of Swords': require('../assets/cards/Knight of Swords.jpg'),
  'Knight of Wands': require('../assets/cards/Knight of Wands.jpg'),
  'Nine of Cups': require('../assets/cards/Nine of Cups.jpg'),
  'Nine of Pentacles': require('../assets/cards/Nine of Pentacles.jpg'),
  'Nine of Swords': require('../assets/cards/Nine of Swords.jpg'),
  'Nine of Wands': require('../assets/cards/Nine of Wands.jpg'),
  'Page of Cups': require('../assets/cards/Page of Cups.jpg'),
  'Page of Pentacles': require('../assets/cards/Page of Pentacles.jpg'),
  'Page of Swords': require('../assets/cards/Page of Swords.jpg'),
  'Page of Wands': require('../assets/cards/Page of Wands.jpg'),
  'Queen of Cups': require('../assets/cards/Queen of Cups.jpg'),
  'Queen of Pentacles': require('../assets/cards/Queen of Pentacles.jpg'),
  'Queen of Swords': require('../assets/cards/Queen of Swords.jpg'),
  'Queen of Wands': require('../assets/cards/Queen of Wands.jpg'),
  'Seven of Cups': require('../assets/cards/Seven of Cups.jpg'),
  'Seven of Pentacles': require('../assets/cards/Seven of Pentacles.jpg'),
  'Seven of Swords': require('../assets/cards/Seven of Swords.jpg'),
  'Seven of Wands': require('../assets/cards/Seven of Wands.jpg'),
  'Six of Cups': require('../assets/cards/Six of Cups.jpg'),
  'Six of Pentacles': require('../assets/cards/Six of Pentacles.jpg'),
  'Six of Swords': require('../assets/cards/Six of Swords.jpg'),
  'Six of Wands': require('../assets/cards/Six of Wands.jpg'),
  'Strength': require('../assets/cards/Strength.jpg'),
  'Temperance': require('../assets/cards/Temperance.jpg'),
  'Ten of Cups': require('../assets/cards/Ten of Cups.jpg'),
  'Ten of Pentacles': require('../assets/cards/Ten of Pentacles.jpg'),
  'Ten of Swords': require('../assets/cards/Ten of Swords.jpg'),
  'Ten of Wands': require('../assets/cards/Ten of Wands.jpg'),
  'The Chariot': require('../assets/cards/The Chariot.jpg'),
  'The Devil': require('../assets/cards/The Devil.jpg'),
  'The Emperor': require('../assets/cards/The Emperor.jpg'),
  'The Empress': require('../assets/cards/The Empress.jpg'),
  'The Fool': require('../assets/cards/The Fool.jpg'),
  'The Hanged Man': require('../assets/cards/The Hanged Man.jpg'),
  'The Hermit': require('../assets/cards/The Hermit.jpg'),
  'The Hierophant': require('../assets/cards/The Hierophant.jpg'),
  'The High Priestess': require('../assets/cards/The High Priestess.jpg'),
  'The Lovers': require('../assets/cards/The Lovers.jpg'),
  'The Magician': require('../assets/cards/The Magician.jpg'),
  'The Moon': require('../assets/cards/The Moon.jpg'),
  'The Star': require('../assets/cards/The Star.jpg'),
  'The Sun': require('../assets/cards/The Sun.jpg'),
  'The Tower': require('../assets/cards/The Tower.jpg'),
  'The World': require('../assets/cards/The World.jpg'),
  'Three of Cups': require('../assets/cards/Three of Cups.jpg'),
  'Three of Pentacles': require('../assets/cards/Three of Pentacles.jpg'),
  'Three of Swords': require('../assets/cards/Three of Swords.jpg'),
  'Three of Wands': require('../assets/cards/Three of Wands.jpg'),
  'Two of Cups': require('../assets/cards/Two of Cups.jpg'),
  'Two of Pentacles': require('../assets/cards/Two of Pentacles.jpg'),
  'Two of Swords': require('../assets/cards/Two of Swords.jpg'),
  'Two of Wands': require('../assets/cards/Two of Wands.jpg'),
  'Wheel of Fortune': require('../assets/cards/Wheel of Fortune.jpg')
};

export const APP_IMAGES: {
  crystalBall: ImageSourcePropType;
  cardBack: ImageSourcePropType;
  deskBack: ImageSourcePropType;
} = {
  crystalBall: require('../assets/crystal-ball.png'),
  cardBack: require('../assets/cardBack.jpg'),
  deskBack: require('../assets/deskBack.png'),
}; 
